ARG IMAGE_VERSION_WEB=latest
FROM php:${IMAGE_VERSION_WEB}
# Enable rewrite, MySQL and PDO extensions
RUN a2enmod rewrite && \
    docker-php-ext-install mysqli pdo pdo_mysql && \
    adduser --disabled-password --no-create-home --disabled-login --uid 1000 webapp && \
    usermod -a -G webapp www-data
